#!/usr/bin/env python3
"""Regenerate .maestro/learnings/INDEX.md from the per-file frontmatter.

Reads every `.md` file in .maestro/learnings/ except README.md and INDEX.md,
parses minimal YAML frontmatter (source, date, tags, supersedes), groups
entries by tag, and writes a deterministic INDEX.md. Files named in any
other file's `supersedes:` list are hidden from the main tag groupings and
listed under "Superseded" instead.

Run from repo root: `python3 tools/build_learnings_index.py`
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_LEARNINGS_DIR = Path(".maestro/learnings")
SKIP_FILES = {"INDEX.md", "README.md"}


def parse_frontmatter(text: str) -> dict:
    """Parse a tiny subset of YAML: scalar strings and inline lists.

    Returns {} if no frontmatter block. Raises ValueError on malformed input.
    """
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    block = m.group(1)
    out: dict = {}
    for line in block.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"malformed frontmatter line: {line!r}")
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            items = [s.strip().strip("\"'") for s in inner.split(",") if s.strip()]
            out[key] = items
        else:
            out[key] = value.strip("\"'")
    return out


def lead_sentence(text: str) -> str:
    """Return the first sentence of the body (after frontmatter, after any heading)."""
    body = re.sub(r"^---\n.*?\n---\n", "", text, count=1, flags=re.DOTALL)
    para = ""
    for line in body.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            para = stripped
            break
    if not para:
        return ""
    m = re.search(r"(.+?[.!?])(\s|$)", para)
    return m.group(1) if m else para


def load_entries(learnings_dir: Path) -> list[dict]:
    entries = []
    for path in sorted(learnings_dir.glob("*.md")):
        if path.name in SKIP_FILES:
            continue
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        entries.append(
            {
                "filename": path.name,
                "source": fm.get("source", ""),
                "date": fm.get("date", ""),
                "tags": fm.get("tags", []) if isinstance(fm.get("tags"), list) else [],
                "supersedes": fm.get("supersedes", []) if isinstance(fm.get("supersedes"), list) else [],
                "summary": lead_sentence(text),
            }
        )
    return entries


def render(entries: list[dict]) -> str:
    superseded: set[str] = set()
    for e in entries:
        for old in e["supersedes"]:
            superseded.add(old)

    active = [e for e in entries if e["filename"] not in superseded]
    hidden = [e for e in entries if e["filename"] in superseded]

    tag_map: dict[str, list[dict]] = {}
    for e in active:
        for tag in e["tags"] or ["(untagged)"]:
            tag_map.setdefault(tag, []).append(e)

    lines: list[str] = []
    lines.append("# Maestro learnings — index")
    lines.append("")
    lines.append(
        "Generated by `tools/build_learnings_index.py`. Do not edit by hand — "
        "edit the underlying files in this directory and regenerate."
    )
    lines.append("")
    lines.append(f"**Active learnings:** {len(active)} · **Tags:** {len(tag_map)} · **Superseded:** {len(hidden)}")
    lines.append("")

    if not active:
        lines.append("_No learnings recorded yet._")
        lines.append("")
    else:
        lines.append("## By tag")
        lines.append("")
        for tag in sorted(tag_map):
            lines.append(f"### {tag}")
            lines.append("")
            for e in sorted(tag_map[tag], key=lambda x: x["filename"]):
                summary = e["summary"] or "(no summary)"
                lines.append(f"- [`{e['filename']}`](./{e['filename']}) — {summary}")
            lines.append("")

    if hidden:
        lines.append("## Superseded")
        lines.append("")
        lines.append("These files are kept for audit but are no longer current. The refined version is linked.")
        lines.append("")
        replacements = {
            old: e["filename"] for e in entries for old in e["supersedes"]
        }
        for e in sorted(hidden, key=lambda x: x["filename"]):
            replaced_by = replacements.get(e["filename"], "?")
            lines.append(f"- [`{e['filename']}`](./{e['filename']}) → superseded by [`{replaced_by}`](./{replaced_by})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dir",
        type=Path,
        default=DEFAULT_LEARNINGS_DIR,
        help="learnings directory (default: .maestro/learnings)",
    )
    args = parser.parse_args()
    if not args.dir.is_dir():
        print(f"learnings dir not found: {args.dir}", file=sys.stderr)
        return 1
    entries = load_entries(args.dir)
    rendered = render(entries)
    index_file = args.dir / "INDEX.md"
    index_file.write_text(rendered, encoding="utf-8")
    superseded = {old for x in entries for old in x["supersedes"]}
    active = sum(1 for e in entries if e["filename"] not in superseded)
    print(f"wrote {index_file} — {active} active / {len(entries)} total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
